// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// als
List als(arma::mat& X, arma::mat& Theta, arma::mat& Y, arma::mat& R, double lambda, double alpha, int batches, double epsilon, int checkInterval);
RcppExport SEXP recommenderlabrats_als(SEXP XSEXP, SEXP ThetaSEXP, SEXP YSEXP, SEXP RSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP batchesSEXP, SEXP epsilonSEXP, SEXP checkIntervalSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP );
        Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP );
        Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< int >::type batches(batchesSEXP );
        Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP );
        Rcpp::traits::input_parameter< int >::type checkInterval(checkIntervalSEXP );
        List __result = als(X, Theta, Y, R, lambda, alpha, batches, epsilon, checkInterval);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP recommenderlabrats_rcpp_hello_world() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = rcpp_hello_world();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
