# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

als <- function(X, Theta, Y, R, lambda, alpha, batches, epsilon, checkInterval) {
    .Call('recommenderlabrats_als', PACKAGE = 'recommenderlabrats', X, Theta, Y, R, lambda, alpha, batches, epsilon, checkInterval)
}

rcpp_hello_world <- function() {
    .Call('recommenderlabrats_rcpp_hello_world', PACKAGE = 'recommenderlabrats')
}

