# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alsCost <- function(X, Theta, Y, R, lambda) {
    .Call('recommenderlabrats_alsCost', PACKAGE = 'recommenderlabrats', X, Theta, Y, R, lambda)
}

alsUpdateX <- function(X, Theta, Y, R, lambda, alpha, batchMode) {
    invisible(.Call('recommenderlabrats_alsUpdateX', PACKAGE = 'recommenderlabrats', X, Theta, Y, R, lambda, alpha, batchMode))
}

alsUpdateTheta <- function(X, Theta, Y, R, lambda, alpha, batchMode) {
    invisible(.Call('recommenderlabrats_alsUpdateTheta', PACKAGE = 'recommenderlabrats', X, Theta, Y, R, lambda, alpha, batchMode))
}

als <- function(init_X, init_Theta, Y, R, lambda, alpha, batches, epsilon, checkInterval, batchMode) {
    .Call('recommenderlabrats_als', PACKAGE = 'recommenderlabrats', init_X, init_Theta, Y, R, lambda, alpha, batches, epsilon, checkInterval, batchMode)
}

updateImplicitX <- function(X, Y, P, C, lambda) {
    invisible(.Call('recommenderlabrats_updateImplicitX', PACKAGE = 'recommenderlabrats', X, Y, P, C, lambda))
}

updateImplicitY <- function(X, Y, P, C, lambda) {
    invisible(.Call('recommenderlabrats_updateImplicitY', PACKAGE = 'recommenderlabrats', X, Y, P, C, lambda))
}

implicitCost <- function(X, Y, P, C, lambda) {
    .Call('recommenderlabrats_implicitCost', PACKAGE = 'recommenderlabrats', X, Y, P, C, lambda)
}

implicit <- function(init_X, init_Y, P, C, lambda, batches, epsilon, checkInterval) {
    .Call('recommenderlabrats_implicit', PACKAGE = 'recommenderlabrats', init_X, init_Y, P, C, lambda, batches, epsilon, checkInterval)
}

explain_predict <- function(X, Y, P, C, lambda, u) {
    .Call('recommenderlabrats_explain_predict', PACKAGE = 'recommenderlabrats', X, Y, P, C, lambda, u)
}

rcpp_hello_world <- function() {
    .Call('recommenderlabrats_rcpp_hello_world', PACKAGE = 'recommenderlabrats')
}

